export const FETCH_USERS_TODOS_REQUEST = 'FETCH_USERS_TODOS_REQUEST';
export const FETCH_USERS_TODOS_SUCCESS = 'FETCH_USERS_TODOS_SUCCESS';
export const FETCH_USERS_TODOS_FAILURE = 'FETCH_USERS_TODOS_FAILURE';